In [1]:
# Importamos las librerías

import pandas as pd
import numpy as np

In [2]:
# Ruta del dataset

ruta_csv = "data/sudoku.csv"


# Cargamos una muestra de 9.000 Sudokus

df = pd.read_csv(
    ruta_csv,
    nrows=9000,
    dtype=str
)


print("Dataset cargado correctamente")
print("Dimensión:", df.shape)

Dataset cargado correctamente
Dimensión: (9000, 2)


In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   puzzle    9000 non-null   str  
 1   solution  9000 non-null   str  
dtypes: str(2)
memory usage: 1.5 MB


In [4]:
# Mostramos las primeras filas

df.head()

,puzzle,solution
0,0700000430400096108006349000940520003584600200...,6795182435437296188216349577943521863584617292...
1,3010865040465210705000000014008000020803479000...,3719865248465213795924738614638197522853479167...
2,0483015603600080909106700030200009355090102006...,7483915623652487919126754834217869355894132766...
3,0083170000042051090000400703271609049014500000...,2983176457642851391539462783271689549814537266...
4,0408906300001368208007405190004670524500207002...,1428956379751368248367425193984671524513287962...


In [5]:
df.columns.tolist()

['puzzle', 'solution']

In [6]:
# Convertimos los Sudokus en matrices

X = np.array(
    [
        list(sudoku)
        for sudoku in df["puzzle"]
    ],
    dtype=np.int8
).reshape(-1, 9, 9)


y = np.array(
    [
        list(sudoku)
        for sudoku in df["solution"]
    ],
    dtype=np.int8
).reshape(-1, 9, 9)


print("Dimensión de X:", X.shape)
print("Dimensión de y:", y.shape)

Dimensión de X: (9000, 9, 9)
Dimensión de y: (9000, 9, 9)


In [7]:
# Mostramos el primer Sudoku

print("PUZZLE")
print(X[0])

print("\nSOLUTION")
print(y[0])

PUZZLE
[[0 7 0 0 0 0 0 4 3]
 [0 4 0 0 0 9 6 1 0]
 [8 0 0 6 3 4 9 0 0]
 [0 9 4 0 5 2 0 0 0]
 [3 5 8 4 6 0 0 2 0]
 [0 0 0 8 0 0 5 3 0]
 [0 8 0 0 7 0 0 9 1]
 [9 0 2 1 0 0 0 0 5]
 [0 0 7 0 4 0 8 0 2]]

SOLUTION
[[6 7 9 5 1 8 2 4 3]
 [5 4 3 7 2 9 6 1 8]
 [8 2 1 6 3 4 9 5 7]
 [7 9 4 3 5 2 1 8 6]
 [3 5 8 4 6 1 7 2 9]
 [2 1 6 8 9 7 5 3 4]
 [4 8 5 2 7 6 3 9 1]
 [9 6 2 1 8 3 4 7 5]
 [1 3 7 9 4 5 8 6 2]]


In [8]:

# Cargamos los primeros 5 registros

df = pd.read_csv(
    "data/sudoku.csv",
    nrows=5,
    dtype=str
)


# Guardamos el nuevo archivo

df.to_csv(
    "data/sudoku_5.csv",
    index=False
)


print("Archivo creado correctamente")
print(df)



Archivo creado correctamente
                                              puzzle  \
0  0700000430400096108006349000940520003584600200...   
1  3010865040465210705000000014008000020803479000...   
2  0483015603600080909106700030200009355090102006...   
3  0083170000042051090000400703271609049014500000...   
4  0408906300001368208007405190004670524500207002...   

                                            solution  
0  6795182435437296188216349577943521863584617292...  
1  3719865248465213795924738614638197522853479167...  
2  7483915623652487919126754834217869355894132766...  
3  2983176457642851391539462783271689549814537266...  
4  1428956379751368248367425193984671524513287962...  
